### PR TITLE
Refactoring: migrate routes to separate modules

### PR DESCRIPTION
**Pull request by JonasBakys0**
## Problem
As the number of routes in main.rs grows, it's essential to keep the file organized.

## Solution
Split routes into separate modules

## Notes
More details - [issue](https://github.com/Sidharth-Singh10/Affinity-backend/issues/1)

## Workflow
- [ ] Initial commit
- [ ] Agree on route groups and solution
- [ ] Finish migration for the rest of the routes

### CODE REVIEW

**Comment by Sidharth-Singh10** [comment]
@JonasBakys0, it's great to see that you are working on the issue.
It is advised that you `sync` your `fork` with upstream `main`.  A lot changes of has taken place.
Please open up a new PR.

**Comment by JonasBakys0** [comment]
@Sidharth-Singh10 Can I just update this one, I already rebased my branch? 😄

**Comment by Sidharth-Singh10** [comment]
Few of your changes are in `main.rs`.
With respect to current state of the repo, your changes should be in `lib.rs`, `main.rs` should not be touched.
You will have to open up a new PR .

**Comment by JonasBakys0** [comment]
I guess it didn't update somehow. Oh well, I will create a new PR

**Pull request closed without merging**
