### PR TITLE
Refactoring: migrate routes to separate modules

### PR DESCRIPTION
**Pull request by JonasBakys0**
## Problem
As the number of routes in `lib.rs` grows, it's essential to keep the file organized.

## Solution
Split routes into separate modules

## Notes
More details - [issue](https://github.com/Sidharth-Singh10/Affinity-backend/issues/1)

## Workflow
- [x] Initial commit
- [ ] Agree on route groups and solution
- [ ] Finish migration for the rest of the routes

### CODE REVIEW

**Comment by JonasBakys0** [comment]
I commented old routes in `lib.rs` and grouped them. This is just a suggestion on how they could be grouped.
Also migrated just a couple of routes in case you would like to have different solution for routes modules.

**Comment by Sidharth-Singh10** [comment]
How about we create , the `routes` folder inside `handlers`.  Create file like `auth_routes.rs` where in we import the `handler` functions and create a router. This is way we wouldn't have to touch `handler` files or move its functions
This would be cleaner for a small/medium sized project.

**Comment by Sidharth-Singh10** [comment]
@JonasBakys0, are you working on the issue?

**Comment by JonasBakys0** [comment]
@Sidharth-Singh10 Hey, sorry about the delay, had a busy couple of days. I'm planning to get back to this today's evening or tomorrow

**Comment by Sidharth-Singh10** [comment]
No worries at all! Thanks for the update.

**Comment by JonasBakys0** [comment]
Hey, `handlers` functions in `routes` are definitely nonsense, I don't know why I left them there. But if you ask my `routes` in `handlers` look strange, They are separate things(modules) in my head. 😄  Then for the naming, `routes/auth_route` I would say the word `route` in `auth_route` is redundant.
But if you like I can do it as described.

**Comment by Sidharth-Singh10** [comment]
Go ahead with your approach! I agree that separating routes and handlers makes sense, and the word 'route' in auth_route does feel redundant.

**Pull request merged**
